services:
  app:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - CONFIG_PATH=config/config.yaml
    depends_on:
      - db
    command: go run ./cmd/RESTapi/main.go

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
