  env: "local"
  database:
    host: "db"
    port: 5432
    user: "postgres"
    password: "password"
    dbname: "db"
  http_server:
    address: "0.0.0.0:8081"
    timeout: 4s
    idle_timeout: 60s