  env: "local"
  database:
    host: "localhost"
    port: 5438
    user: "postgres"
    password: "password"
    dbname: "postgres"
  http_server:
    address: "localhost:8081"
    timeout: 4s
    idle_timeout: 60s