  env: "local"
  database:
    host: "localhost"
    port: "5438"
    user: "postgres"
    password: "12345"
    dbname: "postgres"
  http_server:
    address: "localhost:8080"
    timeout: 4s
    idle_timeout: 60s